### ISSUE TITLE
Install Failed - Exitcode 127

### ISSUE THREAD

**Issue by KoVeCo** [ilseh/RestfulCharging#10]
I try to install the Oppleo Service on a Pi (pi3 / Pi3+ and Pi4)

On all systems and a new install on the pi4 I have this error.
Also reading [this thread](https://github.com/ilseh/Oppleo/issues/8). But the system wont connect to db

Using liquibase v3.10.3 

`liquibase at
Release liquibase locks...
install/install.sh: regel 346: /liquibase: Bestand of map bestaat niet
  FAILED! (exitcode 127)
  Run liquibase update...
install/install.sh: regel 356: /liquibase: Bestand of map bestaat niet
  FAILED! (exitcode 127)
`

db is checked and have access with pgAdmin.

Oppleo.log (after reboot)

`2020-11-03 22:53:11,314 - nl.oppleo.config.OppleoSystemConfig - 502 MainProcess - 3069582032 MainThread - DEBUG - Initializing Oppleo System...
2020-11-03 22:53:11,315 - nl.oppleo.config.OppleoSystemConfig - 502 MainProcess - 3069582032 MainThread - DEBUG - Looking for system configuration file /home/pi/Oppleo/src/nl/oppleo/config/oppleo.ini
2020-11-03 22:53:11,317 - nl.oppleo.config.OppleoSystemConfig - 502 MainProcess - 3069582032 MainThread - ERROR - Ini file ERROR: No SIGNATURE in Oppleo
2020-11-03 22:53:11,318 - nl.oppleo.webapp.Oppleo - 502 MainProcess - 3069582032 MainThread - DEBUG - Initializing Oppleo...
2020-11-03 22:53:11,319 - nl.oppleo.webapp.Oppleo - 502 MainProcess - 3069582032 MainThread - DEBUG - sys.version 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] : 
2020-11-03 22:53:12,728 - nl.oppleo.config.OppleoConfig - 502 MainProcess - 3069582032 MainThread - DEBUG - Initializing Oppleo...
2020-11-03 22:53:12,760 - nl.oppleo.models.ChargerConfigModel - 502 MainProcess - 3069582032 MainThread - ERROR - Could not query from charger_config table in database
Traceback (most recent call last):
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column charger_config.http_host does not exist
LINE 1: ...secret_key AS charger_config_wtf_csrf_secret_key, charger_co...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/Oppleo/src/nl/oppleo/models/ChargerConfigModel.py", line 128, in get_config
    .order_by(ChargerConfigModel.modified_at.desc()) \
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column charger_config.http_host does not exist
LINE 1: ...secret_key AS charger_config_wtf_csrf_secret_key, charger_co...
                                                             ^'

'[SQL: SELECT charger_config.charger_name AS charger_config_charger_name, charger_config.charger_tariff AS charger_config_charger_tariff, charger_config.modified_at AS charger_config_modified_at, charger_config.secret_key AS charger_config_secret_key, charger_config.wtf_csrf_secret_key AS charger_config_wtf_csrf_secret_key, charger_config.http_host AS charger_config_http_host, charger_config.http_port AS charger_config_http_port, charger_config.use_reloader AS charger_config_use_reloader, charger_config.factor_whkm AS charger_config_factor_whkm, charger_config.modbus_interval AS charger_config_modbus_interval, charger_config.autosession_enabled AS charger_config_autosession_enabled, charger_config.autosession_minutes AS charger_config_autosession_minutes, charger_config.autosession_energy AS charger_config_autosession_energy, charger_config.autosession_condense_same_odometer AS charger_config_autosession_condense_same_odometer, charger_config.pulseled_min AS charger_config_pulseled_min, charger_config.pulseled_max AS charger_config_pulseled_max, charger_config.gpio_mode AS charger_config_gpio_mode, charger_config.pin_led_red AS charger_config_pin_led_red, charger_config.pin_led_green AS charger_config_pin_led_green, charger_config.pin_led_blue AS charger_config_pin_led_blue, charger_config.pin_buzzer AS charger_config_pin_buzzer, charger_config.pin_evse_switch AS charger_config_pin_evse_switch, charger_config.pin_evse_led AS charger_config_pin_evse_led, charger_config.peakhours_offpeak_enabled AS charger_config_peakhours_offpeak_enabled, charger_config.peakhours_allow_peak_one_period AS charger_config_peakhours_allow_peak_one_period, charger_config.prowl_enabled AS charger_config_prowl_enabled, charger_config.prowl_apikey AS charger_config_prowl_apikey, charger_config.log_file AS charger_config_log_file, charger_config.webcharge_on_dashboard AS charger_config_webcharge_on_dashboard, charger_config.auth_webcharge AS charger_config_auth_webcharge, charger_config.restrict_dashboard_access AS charger_config_restrict_dashboard_access, charger_config.restrict_menu AS charger_config_restrict_menu, charger_config.allow_local_dashboard_access AS charger_config_allow_local_dashboard_access, charger_config.router_ip_address AS charger_config_router_ip_address, charger_config.receipt_prefix AS charger_config_receipt_prefix 
FROM charger_config ORDER BY charger_config.modified_at DESC 
 LIMIT %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
2020-11-03 22:53:12,782 - nl.oppleo.webapp.Oppleo - 502 MainProcess - 3069582032 MainThread - ERROR - DbException stopped Oppleo!
2020-11-03 22:53:12,782 - nl.oppleo.webapp.Oppleo - 502 MainProcess - 3069582032 MainThread - ERROR - Running Oppleo in limp mode...
`

**Comment by laemen** [comment]
Hi KoVeCo,

please make sure you pull the latest software, made a change which removes the http_port field from the database. In limp mode - when it cannot connect to the database - the web front should still be available at the configured port, so moved the setting to the ini file ( /home/pi/Oppleo/src/nl/oppleo/config/oppleo.ini ). Please find the example in /home/pi/Oppleo/src/nl/oppleo/config/oppleo.example.ini

The line 
```
psycopg2.errors.UndefinedColumn: column charger_config.http_host does not exist
LINE 1: ...secret_key AS charger_config_wtf_csrf_secret_key, charger_co...
```
suggests it can access the database, to the database_url field should be properly configured in /home/pi/Oppleo/src/nl/oppleo/config/oppleo.ini. It should contain a table named charger_config with columns and a single row.  

To update the database you can run the install script ( /home/pi/Oppleo/install/install.sh ) or run the database update manually ( liquibase update ).

I appologize for the inconvenience. Hope this helps.

**Comment by laemen** [comment]
Did you manage to get it working?
